pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                dir('backend') {
                    git branch: 'main',
                    url: 'https://github.com/vaibhavm2344/masterAnything-backend.git'
                }
            }
        }
    }
}